#!/bin/bash
STEP=$1
[ -n "$STEP" ] || exit 1

mpc -q volume "$STEP"

# Turns a string like " 50%" into "50"
VOLUME=$(mpc status '%volume%' | awk -F "%" '{print $1}' | xargs)

notify-send -t 1000 -r 27072 "MPD Volume: $VOLUME%" -h int:value:$VOLUME
